global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Consumer service metrics
  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # ML Service metrics  
  - job_name: 'ml-service'
    static_configs:
      - targets: ['ml-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # RabbitMQ metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 30s

  # PostgreSQL metrics (if we add postgres_exporter later)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
  #   scrape_interval: 30s 